In [1]:
import numpy as np
import data_structure as ds
import abstract as ab
import explicit as ex
import optimization as opt
from decoding_proced import matchingpursuit_explicit, matchingpursuit_abstract
import quantum_opt as qt_opt
import quantum_map as qm

In [2]:
#example
number_spins = 7

#abstract
spectrum_bin = [
    [0,0,0,0,0,1,0],
    [0,1,1,1,0,1,0],
    [0,0,1,1,1,1,0],
    [1,1,1,1,0,0,1]
]
spectrum_pos = [ds.dit_string_to_integer(s) for s in spectrum_bin]
spectrum_val = [-0.5,1.8,-0.3,1.5]

#explicit
full_spectrum = np.zeros((2**number_spins,))
full_spectrum[spectrum_pos] = spectrum_val

In [3]:
interaction_size = 4
constraints = ab.constraints_for_nearest_neighbors_interactions(number_spins, interaction_size, 2)
y = ab.compute_marginal(spectrum_bin, spectrum_val, constraints)
opt.spin_chain_nn_max(y, number_spins, interaction_size)

58

In [4]:
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=3, step=None, interaction_size=interaction_size))
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=3, step=None, interaction_size=interaction_size, opt_func=opt.dual_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=3, step=None, interaction_size=interaction_size, opt_func=opt.simulated_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))

[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]
[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]
[[5.70000e+01 2.02500e+00]
 [1.22000e+02 1.59375e+00]
 [9.00000e+01 1.03125e-01]]


In [23]:
sketch = ex.nearest_neighbors_interactions_sketch(7,interaction_size)
y = ex.compute_marginal(full_spectrum, sketch)
print(matchingpursuit_explicit(y,sketch,3))
print(matchingpursuit_explicit(y,sketch,3, opt_func=opt.spin_chain_nn_max, opt_func_kwargs={"dit_string_length":7, "interaction_size":interaction_size}))
print(matchingpursuit_explicit(y,sketch,3, opt_func=opt.dual_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))
print(matchingpursuit_explicit(y,sketch,3, opt_func=opt.simulated_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))

[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]
[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]
[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]
[[5.80000e+01 2.17500e+00]
 [1.21000e+02 1.40625e+00]
 [8.90000e+01 4.68750e-02]]


In [2]:
#example 2
number_spins = 6

#abstract
spectrum_bin = [
    [0,0,0,0,0,0],
    [0,1,0,1,0,1],
    [0,0,1,0,0,1],
    [1,1,1,1,1,1]
]
spectrum_pos = [ds.dit_string_to_integer(s) for s in spectrum_bin]
spectrum_val = [0.5,5,3,2]

#explicit
full_spectrum = np.zeros((2**number_spins,))
full_spectrum[spectrum_pos] = spectrum_val

In [3]:
interaction_size = 2
constraints = ab.constraints_for_nearest_neighbors_interactions(number_spins, interaction_size, 2)
y = ab.compute_marginal(spectrum_bin, spectrum_val, constraints)
t = opt.spin_chain_nn_max(y, number_spins, interaction_size)
# t = opt.simulated_annealing(y, constraints, number_spins, interaction_size)
ds.integer_to_dit_string(t, number_spins)

array([0, 1, 0, 1, 0, 1])

In [ ]:
#Classical methods
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=2, step=None, interaction_size=interaction_size))
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=2, step=None, interaction_size=interaction_size, opt_func=opt.dual_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=2, step=None, interaction_size=interaction_size, opt_func=opt.simulated_annealing, opt_func_kwargs={"dit_constraints":constraints, "dit_string_length":number_spins}))

[[21.    5.6 ]
 [ 9.    3.08]]
[[21.    5.6 ]
 [ 9.    3.08]]
[[21.    5.6 ]
 [ 9.    3.08]]


In [ ]:
#Quantum methods
print(matchingpursuit_abstract(y, constraints, number_spins, iteration_number=2, step=None, interaction_size=interaction_size, opt_func=qt_opt.digital_annealing))

[[21.    5.6 ]
 [ 9.    3.08]]
